// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Message struct {
	UserID  string `json:"userId"`
	Message string `json:"message"`
}

type NewLink struct {
	Link   string `json:"link"`
	UserID string `json:"user_id"`
}

type NewPost struct {
	Text           string `json:"text"`
	UserID         string `json:"user_id"`
	AttachmentLink string `json:"attachment_link"`
}

type NewUser struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type Search struct {
	Post []*Post `json:"post"`
	User []*User `json:"user"`
}
